user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /
# user:
#     resource: "@UserBundle/Resources/config/routing.yml"
#     prefix:   /
