EventBundle_event_annotation:
    resource: "@EventBundle/Controller"
    prefix: /events
    type: annotation
event_event:
    resource: "@EventBundle/Resources/config/routing/event.php"
    prefix:   /event

event_homepage:
    path:     /hello/{name}
    defaults: { _controller: EventBundle:Default:index }
event_anotherpage:
    path:     /another-page
    defaults: { _controller: EventBundle:Default:another }
