<?php

namespace Me\EventBundle\Repository;

/**
 * ListenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListenerRepository extends \Doctrine\ORM\EntityRepository
{
}
